name: cam_allwinner_nilsimsa_identicalDevices
mode: TrainAndTest
model_quality: best_quality
downsample:
    stratify_by: class
    # sample_ratio: 0.001
    sample_ratio: "minimum"
data:
    to_skip:
        - "128_4_2"
        - "128_4_3"
        - "128_4_4"
        - "128_5_2"
        - "128_5_3"
        - "128_5_4"
        - "128_5_5"
        - "128_6_2"
        - "128_6_3"
        - "128_6_4"
        - "128_6_5"
        - "128_6_6"
        - "256_4_2"
        - "256_4_3"
        - "256_4_4"
        - "256_5_2"
        - "256_5_4"
        - "256_5_5"
        - "256_6_2"
        - "256_6_3"
        - "256_6_4"
        - "256_6_5"
        - "256_6_6"
        - "512_4_2"
        - "512_4_3"
        - "512_4_4"
        - "512_5_2"
        - "512_5_3"
        - "512_5_4"
        - "512_5_5"
        - "512_6_2"
        - "512_6_3"
        - "512_6_4"
        - "512_6_5"
        - "512_6_6"
        - "1024_4_2"
        - "1024_4_3"
        - "1024_4_4"
        - "1024_5_2"
        - "1024_5_3"
        - "1024_5_4"
        - "1024_5_5"
        - "1024_6_2"
        - "1024_6_3"
        - "1024_6_4"
        - "1024_6_5"
        - "1024_6_6"
    accumulator: 
        - 256
    window: 
        - 5
    classes:
    - class:
        label: cam_allwinner-1_cleaned_nilsimsa
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned_nilsimsa/
        device: cam_allwinner-1
    - class: 
        label: cam_allwinner-2_cleaned_nilsimsa
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned_nilsimsa/
        device: cam_allwinner-2
    - class: 
        label: cam_allwinner-3_cleaned_nilsimsa
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned_nilsimsa/
        device: cam_allwinner-3
    - class: 
        label: cam_allwinner-4_cleaned_nilsimsa
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned_nilsimsa/
        device: cam_allwinner-4
    - class: 
        label: cam_allwinner-5_cleaned_nilsimsa
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned_nilsimsa/
        device: cam_allwinner-5
    - class:
        label: cam_allwinner-6_cleaned_nilsimsa
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned_nilsimsa/
        device: cam_allwinner-6
    - class: 
        label: cam_allwinner-7_cleaned_nilsimsa
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned_nilsimsa/
        device: cam_allwinner-7
    - class: 
        label: cam_allwinner-8_cleaned_nilsimsa
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned_nilsimsa/
        device: cam_allwinner-8

