name: deviceGenre_oneRunTest_withNoise
mode: TrainAndTest
model_quality: best_quality
downsample:
    stratify_by: class
    # sample_ratio: 1.
    # sample_ratio: "minimum"
    sample_ratio: "SelectMaxN"
    MaxN: 229168
data:
    to_skip:
        - "1024_4_3"
        - "1024_4_4"
        - "1024_5_2"
        - "1024_5_3"
        - "1024_5_4"
        - "1024_5_5"
        - "1024_6_3"
        - "1024_6_4"
        - "1024_6_5"
        - "1024_6_6"
    accumulator: 
        - 1024
    window: 
        - 5
        - 6
    classes:
    - class:
        label: plug
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: plug_cleaned/
        device: plug-1
    - class: 
        label: plug
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: plug_cleaned/
        device: plug-2
    - class: 
        label: plug
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: plug_cleaned/
        device: plug-3
    - class: 
        label: plug
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: plug_cleaned/
        device: plug-4
    - class: 
        label: plug
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: plug_cleaned/
        device: plug-5
    - class:
        label: plug
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: plug_cleaned/
        device: plug-6
    - class: 
        label: plug
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: plug_cleaned/
        device: plug-7
    - class: 
        label: plug
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: plug_cleaned/
        device: plug-8
    - class: 
        label: light
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: light_cleaned/
        device: light-1
    - class: 
        label: light
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: light_cleaned/
        device: light-2
    - class: 
        label: light
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: light_cleaned/
        device: light-3
    - class: 
        label: light
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: light_cleaned/
        device: light-4
    - class: 
        label: light
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: light_cleaned/
        device: light-5
    - class:
        label: light
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: light_cleaned/
        device: light-6
    - class: 
        label: light
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: light_cleaned/
        device: light-7
    - class: 
        label: light
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: light_cleaned/
        device: light-8
    - class:
        label: cam_allwinner
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned/
        device: cam_allwinner-1
    - class: 
        label: cam_allwinner
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned/
        device: cam_allwinner-2
    - class: 
        label: cam_allwinner
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned/
        device: cam_allwinner-3
    - class: 
        label: cam_allwinner
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned/
        device: cam_allwinner-4
    - class: 
        label: cam_allwinner
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned/
        device: cam_allwinner-5
    - class:
        label: cam_allwinner
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned/
        device: cam_allwinner-6
    - class: 
        label: cam_allwinner
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned/
        device: cam_allwinner-7
    - class: 
        label: cam_allwinner
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/similar_devices_Hashes/
        path_to_inner_data_dir: cam_allwinner_cleaned/
        device: cam_allwinner-8
    - class: 
        label: network_noise
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/noise_Hashes/
        path_to_inner_data_dir: network_noise_cleaned/
        device: network_noise_cleaned
    - class: 
        label: iot_noise
        path_to_outer_data_dir: /storage/nate/SmartRecon/FlexHash/noise_Hashes/
        path_to_inner_data_dir: iot_noise_cleaned/
        device: iot_noise_cleaned